### ISSUE TITLE
Not really an issue!

### ISSUE THREAD

**Issue by miketheanimal** [fabriciovergal/react-native-workers#1]
I've been using https://github.com/devfd/react-native-workers for a while with react native around 0.30.0, which worked OK, but I'm now trying to get stuff working with 0.40.0. 

https://github.com/devfd/react-native-workers seems to be dead (not updated in 6 months) and the fork
https://github.com/fabriciovergal/react-native-workers hasn't been updated in 3 months.

So I'm guessing this is the one to go with ... can you give a bit of info on the state of the project?

**Comment by fabriciovergara** [comment]
This project is functional, but I could not perform heavy tests yet, please try the example :)

I have tried devfds solution, but in his project you need to run react-native bundle every time you change the worker code because its not functional with chrome debugging.

I tried to work in a fork from devfds project, but to make its works with development mode and RN 0.40 was needed a complete rework, so I started from scratch.

Currently I'm trying to find a good way add the following features:
* Start and Stop workers on runtime without interfearing the main bundle debug
* Start worker for scheduled background tasks 

I will create a fork/PR on devfds  project to fix the RN .40 compability, but first I need some free time haha

**Comment by miketheanimal** [comment]
Cool, thanks. Debugging the workers is a definite problem. I resorted to having a build-time option so I could run the code synchronously to debug it as much as I could; and the bundling issue was/is a real pain.

A RN.40 devfds fix would be nice, but don't do it on my account .... your project looks much more interesting, and most of the dev work is done using react-native-web at the moment

**Comment by fabriciovergara** [comment]
Thanks :) 

I was going to create the pr anyway,  I already have something for iOS, android is challenge in this case. 

I'm mostly android developer,  so a created the js api in the same I would do in a java project, but further Ill provide a wrapper to follow web worker api. 

One of my objectives is to be able to toggle programatically the worker debugger and forward any error through a callback on main app to possible to use realm-js on dev mode even with the performance issue on chrome debug issue. I'm currently working in an app with a giant data flow and this issue is making me crazy!
